version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      # Connection string for Postgres in the management app
      ConnectionStrings__AoaiProxyContext: Host=db:5432;Username=admin;Password=mypassword123;Database=aoai-proxy
      PostgresEncryptionKey: myencryptionkey123

  db:
    image: postgres:16.1-alpine
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: aoai-proxy
